DROP TABLE IF EXISTS ga911.site_structure_address_points CASCADE;
BEGIN;
CREATE TABLE ga911.site_structure_site_structure_address_points();
ALTER TABLE ga911.site_structure_address_points ADD COLUMN ogc_fid SERIAL CONSTRAINT site_structure_address_points_pk PRIMARY KEY;
SELECT AddGeometryColumn('public','site_structure_address_points','wkb_geometry',4326,'POINT',2);
ALTER TABLE ga911.site_structure_address_points ADD COLUMN objectid NUMERIC(20,0);
ALTER TABLE ga911.site_structure_address_points ADD COLUMN discrpagid VARCHAR(75);
ALTER TABLE ga911.site_structure_address_points ADD COLUMN dateupdate timestamp with time zone;
ALTER TABLE ga911.site_structure_address_points ADD COLUMN effective timestamp with time zone;
ALTER TABLE ga911.site_structure_address_points ADD COLUMN expire timestamp with time zone;
ALTER TABLE ga911.site_structure_address_points ADD COLUMN site_nguid VARCHAR(254);
ALTER TABLE ga911.site_structure_address_points ADD COLUMN country VARCHAR(2);
ALTER TABLE ga911.site_structure_address_points ADD COLUMN state VARCHAR(2);
ALTER TABLE ga911.site_structure_address_points ADD COLUMN county VARCHAR(40);
ALTER TABLE ga911.site_structure_address_points ADD COLUMN addcode VARCHAR(6);
ALTER TABLE ga911.site_structure_address_points ADD COLUMN adddatauri VARCHAR(254);
ALTER TABLE ga911.site_structure_address_points ADD COLUMN inc_muni VARCHAR(100);
ALTER TABLE ga911.site_structure_address_points ADD COLUMN uninc_comm VARCHAR(100);
ALTER TABLE ga911.site_structure_address_points ADD COLUMN nbrhd_comm VARCHAR(100);
ALTER TABLE ga911.site_structure_address_points ADD COLUMN addnum_pre VARCHAR(15);
ALTER TABLE ga911.site_structure_address_points ADD COLUMN add_number NUMERIC(10,0);
ALTER TABLE ga911.site_structure_address_points ADD COLUMN addnum_suf VARCHAR(15);
ALTER TABLE ga911.site_structure_address_points ADD COLUMN st_premod VARCHAR(15);
ALTER TABLE ga911.site_structure_address_points ADD COLUMN st_predir VARCHAR(9);
ALTER TABLE ga911.site_structure_address_points ADD COLUMN st_pretyp VARCHAR(50);
ALTER TABLE ga911.site_structure_address_points ADD COLUMN st_presep VARCHAR(20);
ALTER TABLE ga911.site_structure_address_points ADD COLUMN st_name VARCHAR(60);
ALTER TABLE ga911.site_structure_address_points ADD COLUMN st_postyp VARCHAR(50);
ALTER TABLE ga911.site_structure_address_points ADD COLUMN st_posdir VARCHAR(9);
ALTER TABLE ga911.site_structure_address_points ADD COLUMN st_posmod VARCHAR(25);
ALTER TABLE ga911.site_structure_address_points ADD COLUMN lst_predir VARCHAR(2);
ALTER TABLE ga911.site_structure_address_points ADD COLUMN lst_name VARCHAR(75);
ALTER TABLE ga911.site_structure_address_points ADD COLUMN lst_type VARCHAR(4);
ALTER TABLE ga911.site_structure_address_points ADD COLUMN lst_posdir VARCHAR(2);
ALTER TABLE ga911.site_structure_address_points ADD COLUMN esn VARCHAR(5);
ALTER TABLE ga911.site_structure_address_points ADD COLUMN msagcomm VARCHAR(30);
ALTER TABLE ga911.site_structure_address_points ADD COLUMN post_comm VARCHAR(40);
ALTER TABLE ga911.site_structure_address_points ADD COLUMN post_code VARCHAR(7);
ALTER TABLE ga911.site_structure_address_points ADD COLUMN post_code4 VARCHAR(4);
ALTER TABLE ga911.site_structure_address_points ADD COLUMN building VARCHAR(75);
ALTER TABLE ga911.site_structure_address_points ADD COLUMN floor VARCHAR(75);
ALTER TABLE ga911.site_structure_address_points ADD COLUMN unit VARCHAR(75);
ALTER TABLE ga911.site_structure_address_points ADD COLUMN room VARCHAR(75);
ALTER TABLE ga911.site_structure_address_points ADD COLUMN seat VARCHAR(75);
ALTER TABLE ga911.site_structure_address_points ADD COLUMN addtl_loc VARCHAR(225);
ALTER TABLE ga911.site_structure_address_points ADD COLUMN landmkname VARCHAR(150);
ALTER TABLE ga911.site_structure_address_points ADD COLUMN mile_post VARCHAR(150);
ALTER TABLE ga911.site_structure_address_points ADD COLUMN place_type VARCHAR(50);
ALTER TABLE ga911.site_structure_address_points ADD COLUMN placement VARCHAR(25);
ALTER TABLE ga911.site_structure_address_points ADD COLUMN long FLOAT8;
ALTER TABLE ga911.site_structure_address_points ADD COLUMN lat FLOAT8;
ALTER TABLE ga911.site_structure_address_points ADD COLUMN elev NUMERIC(10,0);
ALTER TABLE ga911.site_structure_address_points ADD COLUMN fips VARCHAR(5);
ALTER TABLE ga911.site_structure_address_points ADD COLUMN addr_type VARCHAR(5);
ALTER TABLE ga911.site_structure_address_points ADD COLUMN fullstnm VARCHAR(245);
ALTER TABLE ga911.site_structure_address_points ADD COLUMN fulladdr VARCHAR(283);
ALTER TABLE ga911.site_structure_address_points ADD COLUMN abfullstnm VARCHAR(155);
ALTER TABLE ga911.site_structure_address_points ADD COLUMN fulladdnum VARCHAR(38);
ALTER TABLE ga911.site_structure_address_points ADD COLUMN datecreate timestamp with time zone;
ALTER TABLE ga911.site_structure_address_points ADD COLUMN parcel_id VARCHAR(254);
ALTER TABLE ga911.site_structure_address_points ADD COLUMN rcl_nguid VARCHAR(254);
ALTER TABLE ga911.site_structure_address_points ADD COLUMN local_id VARCHAR(140);
CREATE INDEX site_structure_address_points_wkb_geometry_geom_idx ON ga911.site_structure_address_points USING GIST (wkb_geometry);
COMMIT;
